# PLEASE READ THE FILE 'GIT_CONFIG_PATHS' BEFORE CONFIGURATION !!!
# You _really_ need to understand the two set of variables to build
# the final repository path from the Aquarii shell or the WebApp.
application:
  name: III Aquarii
  contact: admin@example.com
  hostname: localhost
  use_rvm: true
pagination:
  per_page: 2
aq_sh:
  user_home: /tmp
  user_name: aq_git
repos:
  root_dir: /tmp
  repo_user: aq_git
git:
  repo_path: git
  have_public_clone: true # global public clone ?
  shell: /opt/local/bin/git-shell
shell:
  path: vendor/aq_sh/aquarii-sh.rb
logs:
  email: email.log
  scm: scm.log
  aq_sh: aq_sh.log
