application:
  name: III Aquarii
  contact: admin@example.com
  hostname: localhost
aq_sh:
  user_home: /tmp
  user_name: aq_git
repos:
  root_dir: /tmp
  repo_user: rhaamo
git:
  repo_path: git
  have_public_clone: true # global public clone ?
  shell: /opt/local/bin/git-shell
shell:
  path: vendor/aq_sh/aquarii-sh.rb
logs:
  email: email.log
  scm: scm.log
  aq_sh: aq_sh.log
